### ISSUE TITLE
Need example snippet to use RGBWLED.ts

### ISSUE THREAD

**Issue by kulkarni-ubisys** [kchinzei/kch-rgbw-lib#1]
@kchinzei 
Can you please provide some examples of how to use the **RGBWLED.ts**
I am completely new to the typescript and facing some issues in using this awesome library.

My end goal is -> I have a LED strip that has 4 primary colors. (They are not standard R,G,B,W,C,M,Y,K, etc)
So, I need a tool to generate RGB to **My4Primaris** conversion matrix and I guess it is achievable with the help of this library.

**Comment by kchinzei** [comment]
Hi, there!

Thank you for your interest to my repository. I am bit lazy on this repository in recent several months and busy for my work, could you be patient around a week to answer?

Regards

Kiyo
K. Chinzei on the mobile

**Comment by kulkarni-ubisys** [comment]
Hello @kchinzei,
Thanks for your reply. Yes, I am gladly waiting for your response. Till them, let me clarify what I am looking for.


----------------------------------------------------------------------------------------------
**// Requirement**
Lets say I have three primaries like following
```
const LEDChipR: LEDChip = new LEDChip('LED_R', { x: 0.6857, y: 0.3143, maxLuminance: 30.6, name: 'Red' });
const LEDChipG: LEDChip = new LEDChip('LED_G', { x: 0.2002, y: 0.6976, maxLuminance: 67.2, name: 'Green' });
const LEDChipB: LEDChip = new LEDChip('LED_B', { x: 0.1417, y: 0.0618, maxLuminance: 8.2,  name: 'Blue' });
```
on hardware level, I can control them using 8bit PWM i.e. PWM(0) = Off, PWM(255) = Maximum bright;
and I want to show a complete red colour
`['rgb', 1,  0,  0]`
or lets say
`['xyY', 0.67,  0.31,  90]`

So the resulting LED brightness should be something like
`R = 255, G = 0, B = 0`

----------------------------------------------------------------------------------------------
**// Analysis of your code**
After looking at the src files and test scripts, I updated test-RGBWLED a bit and now it looks something like
```
// @ts-ignore: TS6133 List all available items for future tests
import { CSpace, CSpaceTypes, LEDChip, RGBWLED, makeGamutContour, GamutError } from '../src/index';
// @ts-ignore: TS6133 List all available items for future tests

const LEDChipR: LEDChip = new LEDChip('LED_R', { x: 0.6857, y: 0.3143, maxLuminance: 30.6, name: 'Red' });
const LEDChipG: LEDChip = new LEDChip('LED_G', { x: 0.2002, y: 0.6976, maxLuminance: 67.2, name: 'Green' });
const LEDChipB: LEDChip = new LEDChip('LED_B', { x: 0.1417, y: 0.0618, maxLuminance: 8.2,  name: 'Blue' });
const LEDChipW: LEDChip = new LEDChip('LED_W', { x: 0.3816, y: 0.3678, maxLuminance: 80.0, name: 'White' });
const LEDChipA: LEDChip = new LEDChip('LED_Other', { x: 0.38, y: 0.58, maxLuminance: 50, name: 'Amb' });
const LEDChipT: LEDChip = new LEDChip('LED_Other', { x: 0.15, y: 0.40, maxLuminance: 70, name: 'Tur' });
const LEDChipV: LEDChip = new LEDChip('LED_Other', { x: 0.25, y: 0.05, maxLuminance: 5,  name: 'Vio' });

class idLED extends LEDChip {
  id: number;
  constructor(led: LEDChip, i: number) {
    super(led);
    this.id = i;
  }
}
const R: idLED = new idLED(LEDChipR, 0);
const G: idLED = new idLED(LEDChipG, 1);
const B: idLED = new idLED(LEDChipB, 2);
const W: idLED = new idLED(LEDChipW, 3);
const A: idLED = new idLED(LEDChipA, 4);
const T: idLED = new idLED(LEDChipT, 5);
const V: idLED = new idLED(LEDChipV, 6);
const idLEDs: idLED[] = [ R,G,B,W,A,T,V ];

const defaultIDList = [
  [ 0, 1, 2 ]
];

let i = 1;


describe.each([
  ['rgb', 1,  0,  0, 0.1, 1],
  ['rgb', 0,  1,  0, 0.1, 1],
  ['rgb', 0,  0,  1, 0.1, 1],
  ['rgb', 0.8,  0.8,  0.8, 0.1, 1]
])('', (t1, q0, q1, q2, brightness, precision) => {
  test(`${i++}. set color().`, async () => {
    for (let j=0; j<defaultIDList.length; j++) {
      const N = defaultIDList[j].length;
      if (N <= RGBWLED.maxLEDNumber) {
        const lList: idLED[] = new Array(N) as idLED[];
        for (let k=0; k<N; k++) {
          const val = defaultIDList[j][k];
          lList[k] = idLEDs[val];
        }
        const l: RGBWLED = new RGBWLED('sample', lList);
        l.brightness = brightness;

        const c: CSpace = new CSpace(t1 as CSpaceTypes, [q0, q1, q2]);
        const maxB = await l.maxBrightnessAtAsync(c);
        const alpha = await l.color2AlphaAsync(c);
        console.log('c is -> ');
        console.log(c);
        console.log('alpha is -> ');
        console.log(alpha);
        console.log('maxB is -> ');
        console.log(maxB);
        
      }
    }
  });
});
```
The same file can be downloaded from this link -> [test-RGBWLED.zip](https://github.com/kchinzei/kch-rgbw-lib/files/6523597/test-RGBWLED.zip)

After running this script I got following in the console log

    c is ->
    CSpace { _type: 'rgb', _a: [ 0.9, 0, 0 ] }
    alpha is ->
    [ 0.006019228107229135, 0.0004056642066214081, 0.0001451213699792376 ]
    maxB is ->
    0.3332700406912907

    c is ->
    CSpace { _type: 'rgb', _a: [ 0, 1, 0 ] }
    alpha is ->
    [ 0.002557326244310947, 0.009447663314476001, 0.00024774660869483355 ]
    maxB is ->
    0.7141315386720938

    c is ->
    CSpace { _type: 'rgb', _a: [ 0, 0, 1 ] }
    alpha is ->
    [
      0.00020089889000256614,
      -0.00011599796383091721,
      0.009004863065287722
    ]
    maxB is ->
    -1

    c is ->
    CSpace { _type: 'rgb', _a: [ 0.8, 0.8, 0.8 ] }
    alpha is ->
    [ 0.005300066232767856, 0.00587966579412165, 0.0056746069275536454 ]
    maxB is ->
    0.9688449284794375

----------------------------------------------------------------------------------------------
**// Questions**

- I was expecting the resulting alpha values close to 1, showing maximum brightness or something, but I am a bit confused with the obtained results and the maxB values.
- It would be really helpful if you can elaborate more on the console logs, if they are correct, how?
- If not how should I proceed with it?

**Comment by kchinzei** [comment]
The output you get is as expected. Here is why:

- Class RGBWLED uses absolute luminosity to calculate alphas. RGB and HSV indeed do not have absolute luminosity.
- In your example, you tested using RGB=(1,0,0) etc, which gives Y value (luminosity) of XYZ  = 0.21 and used this as luminosity.
- In your example, R,G,B LEDs with 30.6, 67.2 and 8.2 luminosity. Calculating alphas for Y=0.21 gives small values.
- maxBrightnessAtAsync(c) gives (max luminosity at color c for given LED combination) / (max luminosity when turn on all LEDs). I get 35.32 for RGB=(1,0,0). 35.32 / (30.6 + 67.2 + 8.20) = 0.333207547169811
- RGB=(0,0,1) appears outside the gamut of three LEDs therefore gives one negative alpha which is physically not possible.

For your application, you need to specify some value as luminosity (or brightness). For example,
`let c2 = c.xyY();
c2.brightness = 0.8; // Beware, it can be beyond LED's capacity depending on the color.
const alpha = await l.color2AlphaAsync(c2);
...`

**Comment by kchinzei** [comment]
kulkarni-ubisys,

Some code snippets are in docs/snippets.md, currently at develop branch.
https://github.com/kchinzei/kch-rgbw-lib/tree/develop
